export const servicesBox = [
    {
        id: "servisi1",
        // serviceBoxClass1: styles.serviceBoxFirst,
        // img1Src: tooth,
        img1Alt: "tooth-svg",
        // imgClass: styles.toothImage,
        dataValue: "5",
        // img2Src: toothBlush,
        img2Alt: "teethBlush-svg",
        // img2class: styles.teethBlush,
        h4: "კოსმეტიკა",
        p: "გენერატორით შექმნილი ტექსტის გამოყენება, რადგან უბრალოდ „ტექსტი ტექსტი ტექსტი",
    },
    {
      id: "servisi2",
        // serviceBoxClass1: styles.serviceBoxSecond,
        href: '/services/მკურნალობა',
        // img1Src: tooth,
        img1Alt: "tooth-svg",
        // imgClass: styles.toothImage,
        dataValue: "-5",
        // img2Src: mouth,
        img2Alt: "teethBlush-svg",
        // img2class: styles.mouth,
        h4: "მკურნალობა",
        p: "გენერატორით შექმნილი ტექსტის გამოყენება, რადგან უბრალოდ „ტექსტი ტექსტი ტექსტი",
    },
    {
      id: "servisi3",
        // serviceBoxClass1: styles.serviceBoxThird,
        href: '/services/კბილისოპერაცია',
        // img1Src: tooth,
        img1Alt: "tooth-svg",
        // imgClass: styles.toothImage,
        dataValue: "3",
        // img2Src: operation,
        img2Alt: "teethBlush-svg",
        // img2class: styles.operation,
        h4: "კბილის ოპერაცია",
        p: "გენერატორით შექმნილი ტექსტის გამოყენება, რადგან უბრალოდ „ტექსტი ტექსტი ტექსტი",
    },
    {
      id: "servisi4",
        // serviceBoxClass1: styles.serviceBoxFourth,
        href: "/services/კბილისგათეთრება",
        // img1Src: tooth,
        img1Alt: "tooth-svg",
        // imgClass: styles.toothImage,
        dataValue: "-3",
        // img2Src: toothFilling,
        img2Alt: "teethBlush-svg",
        // img2class: styles.toothFilling,
        h4: "კბილის გათეთრება",
        p: "გენერატორით შექმნილი ტექსტის გამოყენება, რადგან უბრალოდ „ტექსტი ტექსტი ტექსტი",
    },
  ]